name: umpire-quiz

services:

  question-service:
    build: question_service
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9080/health/ready" ]
      interval: 2s
      timeout: 10s
      retries: 24
      start_period: 10s
    ports:
      - "9080:9080"
    environment:
      MYSQL_HOSTNAME: "question-service-db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "question-db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USE_SSL: "true"
    depends_on:
      question-service-db:
        condition: service_healthy
    networks:
      - umpire-network

  question-service-db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "question-db"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 10s
      start_period: 2s
      retries: 10
    networks:
      - umpire-network

  importer-service:
    build: importer_service
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9080/health/ready" ]
      interval: 2s
      timeout: 10s
      retries: 24
      start_period: 10s
    ports:
      - "9082:9080"
    environment:
      MYSQL_HOSTNAME: "question-service-db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "question-db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USE_SSL: "true"
    depends_on:
      question-service-db:
        condition: service_healthy
      question-service:
        condition: service_healthy
    networks:
      - umpire-network

volumes:
  mysql-data:

networks:
  umpire-network:
    driver: bridge
